GuyKh/iec-custom-component

custom_components/iec/sensor.py
=> fix: Remove suggested_unit_of_measurement

custom_components/iec/coordinator.py
IEC api returns different values for monthly readings when specifying *today's* date and *1st of the month* date, when it comes to last daily readings...
Instead of sending 1st of the month in the request, sending today....
=> fix: Wrong calculation of Yesterday/Today consumption

custom_components/iec/coordinator.py
```
2024-03-09 00:54:49.382 DEBUG (MainThread) [custom_components.iec.coordinator] Last statistics are from 2024-03-07 23:00:00
2024-03-09 00:54:49.383 DEBUG (MainThread) [custom_components.iec.coordinator] Calculated from_date = 2024-03-08 01:00:00
2024-03-09 00:54:49.383 DEBUG (MainThread) [custom_components.iec.coordinator] The date to fetch is today or later, replacing it with Today at 01:00:00
2024-03-09 00:54:49.384 DEBUG (MainThread) [custom_components.iec.coordinator] Fetching consumption from 2024-03-09 01:00:00
```
=> fix: 23:00 daily fetch

custom_components/iec/config_flow.py, custom_components/iec/coordinator.py, custom_components/iec/manifest.json, custom_components/iec/sensor.py, custom_components/iec/translations/en.json, custom_components/iec/translations/he.json, hacs.json, requirements.txt
=> fix: Multiple Contracts config flow + sensor translations

custom_components/iec/config_flow.py, custom_components/iec/manifest.json
=> Fix: multi contract config flow selection

custom_components/iec/binary_sensor.py, custom_components/iec/sensor.py, custom_components/iec/translations/en.json, custom_components/iec/translations/he.json, requirements.txt
=> Feat: `amount_to_pay` and `is_last_invoice_paid` sensors

custom_components/iec/coordinator.py, custom_components/iec/sensor.py
=> fix: handle no invoices case with try-expect

custom_components/iec/binary_sensor.py, custom_components/iec/commons.py, custom_components/iec/sensor.py
=> feat: Group entities by Contract and Meter Devices

custom_components/iec/coordinator.py, custom_components/iec/manifest.json
bug_fix
___
- Updated the kWh tariff calculation in `coordinator.py` to directly use the value from the new version of `iec-api` without dividing by 100, fixing the tariff calculation to work correctly with the updated API.
- Improved error logging when fetching the kWh Tariff fails.
- Updated the `iec-api` dependency in `manifest.json` from version 0.2.13 to 0.2.14 to ensure compatibility with the new API version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>coordinator.py</strong><dd><code>Adjust kWh Tariff Calculation and Improve Error Handling</code>&nbsp; </dd></summary>
<hr>
custom_components/iec/coordinator.py
<li>Removed division by 100 for the kWh tariff …
=> fix: Fix tariff with new iec-api version

custom_components/iec/manifest.json, requirements.txt
enhancement
___
- Updated `iec-api` to version 0.2.15 across the project to address an `unhashable` bug.
- Incremented the version of the custom component in `manifest.json` to 0.0.26.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update iec-api version and increment component version</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/iec/manifest.json
<li>Updated the <code>iec-api</code> requirement from version 0.2.14 to 0.2.15.<br> <li> Incremented the component version from 0.0.25 to 0.0.26.<br>
</details>
</td>
<td><a href="https://github.com/GuyKh/iec-custom-component/pull/108/files#diff-21a6d1c0910160ff96d …
=> chore: bump to iec-api 0.2.15 to fix `unhashable` bug

custom_components/iec/coordinator.py
Bug fix
___
- Optimized the handling of datetime localization in the `coordinator.py` by introducing a single instance of the localized current date (`localized_today`).
- This change reduces the redundancy of multiple calls to `TIMEZONE.localize(datetime.today())`, enhancing the efficiency of date manipulations throughout the module.
- Updated various methods to use `localized_today` for date checks and setting, ensuring consistency and reducing overhead.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>coordinator.py</strong><dd><code>Optimize datetime localization in coordinator module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> fix: reduce calls to TIMEZONE.localize

custom_components/iec/manifest.json, requirements.txt
enhancement
___
- This PR updates the `iec-api` library version from 0.2.15 to 0.2.16 in both `manifest.json` and `requirements.txt`.
- The update is intended to address issues related to decimal/float conversions as indicated in the commit message.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>manifest.json</strong><dd><code>Update iec-api library version in manifest</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
custom_components/iec/manifest.json
- Updated the `iec-api` library version from 0.2.15 to 0.2.16.
</details>
</td>
<td><a …
=> chore: bump to 0.2.16 to fix decimal/float issue

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature_request.yml
documentation
___
- Updated the URL in the bug issue template to point to the correct repository for checking duplicate issues.
- Updated the URL in the feature request template to point to the correct repository for checking duplicate feature requests.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>bug.yml</strong><dd><code>Fix URL for duplicate bug issues check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/ISSUE_TEMPLATE/bug.yml
- Updated URL for checking duplicate issues.
</details>
</td>
<td><a …
=> Fix url in ISSUE_TEMPLATE

custom_components/iec/manifest.json, custom_components/iec/sensor.py
=> fix: Fix Custom Attribues value fetching

custom_components/iec/coordinator.py
=>  fix: Wrap _estimate_bill with catch to avoid breaking the component + fix bad device_by_id response

custom_components/iec/commons.py, custom_components/iec/coordinator.py, custom_components/iec/sensor.py
Use Monthly resolution + Today's date to calculate Today/Yesterday usage.
Should address issues #187 #197
=> fix: Wrong Today/Yesterday calculation

custom_components/iec/manifest.json, requirements.txt
=> chore: bump iec-api to 0.4.5

custom_components/iec/coordinator.py
=> fix: Coordinator update fail fallback

custom_components/iec/translations/en.json, custom_components/iec/translations/he.json
=> fix: Not translated `no_contracts`

custom_components/iec/coordinator.py
=> fix: Start fetching from Meter install rather than a month ago

custom_components/iec/coordinator.py
=> fix: Fix Meter Start Date comparison

custom_components/iec/coordinator.py
=> fix: Statistics - compare offset-naive and offset-aware datetimes

custom_components/iec/config_flow.py, custom_components/iec/const.py, custom_components/iec/manifest.json, custom_components/iec/translations/en.json, custom_components/iec/translations/he.json, requirements.txt
Enhancement
___
- Display OTP factor type (Email/SMS) in config flow
- Update IEC API dependency to version 0.4.12
- Add localized descriptions for OTP delivery method
___
```mermaid
flowchart LR
A["Config Flow"] --> B["Login with ID"]
B --> C["Get OTP Type"]
C --> D["Display OTP Form"]
D --> E["Show Delivery Method"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>config_flow.py</strong><dd><code>Capture and display OTP delivery type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> feat: ConfigFlow to show OTP Factor Type (Email/SMS)
